/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    JobEscrow: {
      address: "0xDe70C5326EF0a932fB2Fa56Ecaa2Fb08BC0D7693",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "VALIDATOR_FEE_PERCENT",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "acceptJob",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "acceptorJobs",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "cancelJob",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "completeJob",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "createJob",
          inputs: [
            {
              name: "_title",
              type: "string",
              internalType: "string"
            },
            {
              name: "_description",
              type: "string",
              internalType: "string"
            }
          ],
          outputs: [],
          stateMutability: "payable"
        },
        {
          type: "function",
          name: "disputeJob",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "getJob",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct JobEscrow.Job",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "maker",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "acceptor",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "validator",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum JobEscrow.JobStatus"
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "completedAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "disputedAt",
                  type: "uint256",
                  internalType: "uint256"
                }
              ]
            }
          ],
          stateMutability: "view"
        }, 
       {
          type: "function",
          name: "getJobsByAcceptor",
          inputs: [
            {
              name: "_acceptor",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct JobEscrow.Job[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "maker",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "acceptor",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "validator",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum JobEscrow.JobStatus"
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "completedAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "disputedAt",
                  type: "uint256",
                  internalType: "uint256"
                }
              ]
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getJobsByMaker",
          inputs: [
            {
              name: "_maker",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct JobEscrow.Job[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "maker",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "acceptor",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "validator",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum JobEscrow.JobStatus"
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "completedAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "disputedAt",
                  type: "uint256",
                  internalType: "uint256"
                }
              ]
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getJobsByValidator",
          inputs: [
            {
              name: "_validator",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct JobEscrow.Job[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "maker",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "acceptor",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "validator",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum JobEscrow.JobStatus"
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "completedAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "disputedAt",
                  type: "uint256",
                  internalType: "uint256"
                }
              ]
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getOpenJobs",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "tuple[]",
              internalType: "struct JobEscrow.Job[]",
              components: [
                {
                  name: "id",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "maker",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "acceptor",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "validator",
                  type: "address",
                  internalType: "address"
                },
                {
                  name: "amount",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "title",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string"
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum JobEscrow.JobStatus"
                },
                {
                  name: "createdAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "completedAt",
                  type: "uint256",
                  internalType: "uint256"
                },
                {
                  name: "disputedAt",
                  type: "uint256",
                  internalType: "uint256"
                }
              ]
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getTotalJobs",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getTotalValidators",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "getValidators",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "isValidator",
          inputs: [
            {
              name: "_address",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "jobValidator",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "jobs",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "maker",
              type: "address",
              internalType: "address"
            },
            {
              name: "acceptor",
              type: "address",
              internalType: "address"
            },
            {
              name: "validator",
              type: "address",
              internalType: "address"
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "title",
              type: "string",
              internalType: "string"
            },
            {
              name: "description",
              type: "string",
              internalType: "string"
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum JobEscrow.JobStatus"
            },
            {
              name: "createdAt",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "completedAt",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "disputedAt",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        }, 
       {
          type: "function",
          name: "makerJobs",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "nextJobId",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "registerAsValidator",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "resolveDispute",
          inputs: [
            {
              name: "_jobId",
              type: "uint256",
              internalType: "uint256"
            },
            {
              name: "_approve",
              type: "bool",
              internalType: "bool"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [],
          stateMutability: "nonpayable"
        },
        {
          type: "function",
          name: "validatorList",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256"
            }
          ],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "function",
          name: "validators",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address"
            }
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool"
            }
          ],
          stateMutability: "view"
        },
        {
          type: "event",
          name: "DisputeResolved",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256"
            },
            {
              name: "validator",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "approved",
              type: "bool",
              indexed: false,
              internalType: "bool"
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "JobAccepted",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256"
            },
            {
              name: "acceptor",
              type: "address",
              indexed: true,
              internalType: "address"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "JobCancelled",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256"
            },
            {
              name: "maker",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "refundAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "JobCompleted",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256"
            },
            {
              name: "acceptor",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "JobCreated",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256"
            },
            {
              name: "maker",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256"
            },
            {
              name: "title",
              type: "string",
              indexed: false,
              internalType: "string"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "JobDisputed",
          inputs: [
            {
              name: "jobId",
              type: "uint256",
              indexed: true,
              internalType: "uint256"
            },
            {
              name: "validator",
              type: "address",
              indexed: true,
              internalType: "address"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address"
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address"
            }
          ],
          anonymous: false
        },
        {
          type: "event",
          name: "ValidatorRegistered",
          inputs: [
            {
              name: "validator",
              type: "address",
              indexed: true,
              internalType: "address"
            }
          ],
          anonymous: false
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address"
            }
          ]
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address"
            }
          ]
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: []
        }
      ],
      inheritedFunctions: {},
      deployedOnBlock: 45324202,
    },
  },
} satisfies GenericContractsDeclaration;

export default deployedContracts;